---
- name: "Install Node.js 13" 
  become: true
  shell : |
    # Install Node.js LTS version
    curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
    sudo apt install -y nodejs

    # Use Version manager to use node js v13.8.0
    sudo npm install --global n
    sudo n 13.8.0

- name: "Install PM2 Globally"
  npm:
    name: pm2
    global: yes
